# 🚀 NumPy - Introduction

## What is NumPy?

**NumPy (Numerical Python)** is one of the most popular Python libraries used for **fast numerical computing**. It is specially designed to perform calculations on **large datasets** efficiently using **NumPy Arrays**.

Instead of relying on Python lists and loops, NumPy performs operations using optimized C code behind the scenes, making calculations significantly faster and more memory-efficient.

---

## History of NumPy

NumPy was created by **Travis Oliphant** in **2005**.

Before NumPy, Python programmers mainly used **lists** and **loops** for mathematical calculations. Although Python is easy to use, this approach became very slow when working with millions of data points.

To solve this performance problem, Travis Oliphant developed NumPy, introducing the powerful **ndarray (N-dimensional Array)** data structure.

---

## Why was NumPy created?

Imagine you are calculating the average temperature of:

- 6 cities ✅
- 10,000 cities
- 10 lakh cities
- 5 crore sensor readings

Using Python lists and loops becomes increasingly slow as the amount of data grows.

NumPy solves this problem by storing data efficiently in arrays and performing operations using optimized compiled code.

---

## When should we use NumPy?

### Use Python Lists when

- Dataset is small.
- General-purpose programming.
- Different data types are required.

### Use NumPy when

- Dataset is large.
- Mathematical calculations are needed.
- Machine Learning
- Data Science
- Artificial Intelligence
- Scientific Computing
- Image Processing
- Financial Analysis
- Medical Research

In [ ]:
# Import NumPy library
import numpy as np

# Temperature data of different cities
temperatures = [32.5, 34.2, 31.5, 36.1, 23.4, 35.8]

# Calculate average using NumPy
average = np.mean(temperatures)

print("Average Temperature:", average)

## Explanation

### import numpy as np

Imports the NumPy library.

`np` is the standard alias used worldwide instead of writing `numpy` repeatedly.

---

### temperatures = [...]

Creates a normal Python list containing temperature values.

---

### np.mean(temperatures)

Calculates the arithmetic mean (average) of all values.

Formula

Average = Sum of all values ÷ Total number of values

---

### print()

Displays the result.

# Python List vs NumPy Array

## Python List

A **Python list** is a built-in data structure used to store multiple values in a single variable.

Lists are flexible because they can store different data types, but they are **not optimized for large-scale numerical computations**.

---

## NumPy Array

A **NumPy Array (`ndarray`)** is the fundamental data structure provided by the NumPy library.

Unlike Python lists, NumPy arrays are designed specifically for **fast numerical computation**.

They store elements efficiently in memory and allow mathematical operations to be performed on entire arrays without writing explicit loops.

---

## Python List vs NumPy Array

| Python List | NumPy Array |
|-------------|-------------|
| Built into Python | Provided by NumPy |
| Can store different data types | Usually stores one data type (homogeneous) |
| Slower for numerical computation | Optimized for fast numerical computation |
| Uses more memory | More memory efficient |
| Requires loops for many mathematical operations | Supports vectorized operations |

---

## Why does the output look different?

Python List

```python
[1, 2, 3, 4, 5]
```

NumPy Array

```python
[1 2 3 4 5]
```

The missing commas **do not improve speed**. They are simply part of NumPy's display format.

The real performance improvement comes from:

- Efficient memory layout (contiguous memory)
- Homogeneous data type
- Optimized C implementation
- Vectorized operations

The display format and execution speed are unrelated.

In [ ]:
# Python List Example

python_list = [1, 2, 3, 4, 5]

print(python_list)

### Explanation

```python
python_list = [1, 2, 3, 4, 5]
```

Creates a normal Python list.

---

```python
print(python_list)
```

Displays the list on the screen.

Output:

```python
[1, 2, 3, 4, 5]
```

In [ ]:
# Import NumPy
import numpy as np

# Create a NumPy Array
numpy_array = np.array([1, 2, 3, 4, 5])

print(numpy_array)

### Explanation

```python
import numpy as np
```

Imports the NumPy library.

---

```python
np.array()
```

Creates a **NumPy ndarray (N-dimensional Array)** from a Python list.

**Syntax**

```python
np.array(object)
```

where `object` is typically a list, tuple, or another array-like object.

---

```python
print(numpy_array)
```

Displays the NumPy array.

Output:

```python
[1 2 3 4 5]
```

Notice that NumPy displays elements without commas. This is only a formatting difference and does **not** indicate why NumPy is faster.

In [ ]:
import numpy as np

# Temperature data
temperatures = [32.5, 34.2, 31.5, 36.1, 36.4, 35.8]

# Calculate the average using NumPy
average = np.mean(temperatures)

print(average)

### Explanation

```python
temperatures = [...]
```

Creates a list containing temperature values.

---

```python
np.mean(temperatures)
```

Calculates the arithmetic mean (average) of all values.

Formula:

```
Average = Sum of all values / Number of values
```

For the given data:

```
(32.5 + 34.2 + 31.5 + 36.1 + 36.4 + 35.8) / 6

= 34.416666...

≈ 34.42
```

Depending on floating-point representation, Python may display approximately:

```
34.416666666666664
```

or

```
34.41666666666667
```

Rounded to two decimal places:

```
34.42
```

In [ ]:
# Temperature data
temperatures = [32.5, 34.2, 31.5, 36.1, 36.4, 35.8]

total = 0

# Add each temperature
for temp in temperatures:
    total += temp

# Calculate average
average = total / len(temperatures)

print(average)

### Explanation

```python
total = 0
```

Initializes a variable to store the running total.

---

```python
for temp in temperatures:
```

Iterates through each temperature in the list.

---

```python
total += temp
```

Adds each temperature to the running total.

---

```python
len(temperatures)
```

Returns the total number of elements in the list.

---

```python
average = total / len(temperatures)
```

Calculates the arithmetic mean manually.

This approach works correctly but becomes slower and more verbose for very large datasets compared to using NumPy's optimized functions.

# Arrays in NumPy

## What is an Array?

An **array** is a collection of elements stored together in an organized manner in memory.

In NumPy, arrays are designed for **fast numerical computation** and allow mathematical operations to be performed directly on the entire collection of data.

Unlike creating many separate variables, storing related values in an array makes code cleaner, easier to manage, and more memory efficient.

---

## Example

Instead of writing

```python
mark1 = 89
mark2 = 86
mark3 = 87
mark4 = 97
mark5 = 84
```

we can simply write

```python
marks = [89, 86, 87, 97, 84]
```

or even better, as a NumPy array

```python
marks = np.array([89, 86, 87, 97, 84])
```

This approach is cleaner and is preferred for numerical computations.

---

# Types of NumPy Arrays

## 1D Array (Vector)

A one-dimensional array stores data in a single row (or sequence).

Example

```
[10 20 30 40 50]
```

Also called a **Vector**.

---

## 2D Array (Matrix)

A two-dimensional array stores data in rows and columns.

Example

```
[[1 2 3]
 [4 5 6]]
```

Also called a **Matrix**.

---

## Multidimensional Array (Tensor)

Arrays having **three or more dimensions** are commonly referred to as **Tensors** (especially in Machine Learning and Deep Learning).

Example shape

```
(3, 4, 5)
```

meaning

```
3 matrices
each containing
4 rows
and 5 columns
```

In [ ]:
import numpy as np

# Create a 1D NumPy Array (Vector)
arr_1d = np.array([10, 20, 30, 40, 50])

print(arr_1d)

### `np.array()`

Creates a NumPy array from a Python list.

**Syntax**

```python
np.array(object)
```

Here, the list

```python
[10, 20, 30, 40, 50]
```

is converted into a NumPy **1D array (Vector)**.

In [ ]:
import numpy as np

# Create a 2D NumPy Array (Matrix)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d)

A list of lists creates a **2D NumPy array**.

Each inner list represents one row.

Shape:

```
(2, 3)
```

meaning

- 2 rows
- 3 columns

In [ ]:
import numpy as np

tensor = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(tensor)



# tensor = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])  # 2 matrix with 2row*2colum


This is a **3-dimensional NumPy array**.

Its shape is

```
(2, 2, 2)
```

meaning

- 2 matrices
- each matrix has 2 rows
- each row has 2 columns

In Machine Learning, arrays with three or more dimensions are commonly called **Tensors**.

# 2. Create Array from a Python List

In [ ]:
import numpy as np

arr = np.array([1, 3, 2, 3, 4])

print(arr)

`np.array()` converts a Python list into a NumPy array.

This is the most common way to create an array.

In [ ]:
import numpy as np

# 2D array of zeros
zeros_arr = np.zeros((3, 1))

print(zeros_arr)

### `np.zeros(shape)`

Creates an array filled with **0**.

**Syntax**

```python
np.zeros(shape)
```

Examples

```python
np.zeros(5)
```

Creates a **1D array**

```
[0. 0. 0. 0. 0.]
```

```python
np.zeros((3,1))
```

Creates a **2D array**

Shape

```
(3,1)
```

In [ ]:
import numpy as np

ones_array = np.ones((2, 3))

print(ones_array)

### `np.ones(shape)`

Creates an array where every element is **1**.

Example

```
[[1. 1. 1.]
 [1. 1. 1.]]
```

In [ ]:
import numpy as np

filled_arr = np.full((2, 2), 7)

print(filled_arr)

### `np.full(shape, fill_value)`

Creates an array where every element is the specified value.

Example

```python
np.full((2,2),7)
```

Result

```
[[7 7]
 [7 7]]
```

# 3. User-Defined Filled Array

In [ ]:
import numpy as np

rows = int(input("Enter number of rows: "))
columns = int(input("Enter number of columns: "))
value = int(input("Enter the value to fill: "))

user_array = np.full((rows, columns), value)

print(user_array)

This program creates a NumPy array based on user input.

The user specifies:

- number of rows
- number of columns
- value to fill

In [ ]:
import numpy as np

array = np.arange(1, 11, 2)

print(array)

### `np.arange(start, stop, step)`

Creates evenly spaced values within the specified range.

**Syntax**

```python
np.arange(start, stop, step)
```

Example

```python
np.arange(1,11,2)
```

Output

```
[1 3 5 7 9]
```

The `stop` value is **excluded**, just like Python's `range()`.

In [3]:
import numpy as np

arr = np.linspace(1, 5, 2)

print(arr)

[1. 5.]


### `np.linspace(start, stop, num)`

Generates a specified number of **evenly spaced values** between the start and stop values.

**Syntax**

```python
np.linspace(start, stop, num)
```

Example

```python
np.linspace(1,5,2)
```

Output

```
[1. 5.]
```

Since only **2 values** are requested, NumPy returns the start and end values.

Another example

```python
np.linspace(1,5,5)
```

Output

```
[1. 2. 3. 4. 5.]
```

# 📘 Chapter 4 — Creating Number Sequences & Identity Matrix

# Creating Number Sequences

NumPy provides functions to generate sequences and special matrices without using loops.

In this chapter:

- `np.arange()` (additional examples)
- `np.eye()` (Identity Matrix)

In [ ]:
import numpy as np

# Generate numbers from 1 to 9
arr = np.arange(1, 10)   # (start,stop,step)
print(arr)

# Generate numbers with a step of 2
arr1 = np.arange(1, 10, 2)
print(arr1)

- example:

```python
np.arange(1, 10, 2)
```

- Starts from `1`
- Increments by `2`
- Stops before `10`

In [ ]:
# Create a 3 × 3 Identity Matrix
identity_matrix = np.eye(3)

print(identity_matrix)

### `np.eye()`

Creates an **Identity Matrix**.

**Syntax**

```python
np.eye(N)
```

`N` → Size of the square matrix.


## Identity Matrix

An **Identity Matrix** is a **square matrix** in which:

- Diagonal elements are `1`
- All other elements are `0`

Example:

```
1 0 0
0 1 0
0 0 1
```

# 📘 Chapter 5 — Array Attributes

# Array Attributes

Array attributes provide information about the structure and properties of a NumPy array.

Unlike functions, **attributes DO NOT❌ use parentheses `()`**.

Syntax:

```python
arr.attribute
```

In this chapter:

- `shape`
- `size`
- `ndim`
- `dtype`

In [1]:
import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Shape :", arr_2d.shape)
print("Size  :", arr_2d.size)
print("NDim  :", arr_2d.ndim)
print("DType :", arr_2d.dtype)

Shape : (2, 3)
Size  : 6
NDim  : 2
DType : int64


### `arr.shape`

Returns the array shape.

Output:

```python
(rows, columns)
```

Example:

```python
(2, 3)
```

---

### `arr.size`

Returns the **total number of elements**.

Example:

```
6
```

---

### `arr.ndim`

Returns the **number of dimensions**.

Example:

```
2
```

---

### `arr.dtype`

Returns the data type of array elements.

Example:

```
int64
float64
```

In [5]:
arr_1d = np.array([1, 2, 3])

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr_3d = np.array([
    [
        [1, 2],
        [3, 4],
        [4, 5],
        [6, 7]
    ]
])

# Shape
print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

print()

# Size
print(arr_1d.size)
print(arr_2d.size)
print(arr_3d.size)

print()

# Number of Dimensions
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

print()

# Data Type
print(arr_1d.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)

(3,)
(2, 3)
(1, 4, 2)

3
6
8

1
2
3

int64
int64
int64


### Shape Examples

| Array | Shape |
|-------|--------|
| 1D | `(3,)` |
| 2D | `(2, 3)` |
| 3D | `(1, 4, 2)` |

---

### Dimension Examples

| Array | Dimensions |
|-------|------------|
| 1D | `1` |
| 2D | `2` |
| 3D | `3` |

# 📘 Chapter 5.2 — Changing Data Type (astype())

# Changing Data Type

NumPy provides the **`astype()`** method to convert the data type of an array.

It returns a **new array** with the specified data type, while the original array remains unchanged.

In [ ]:
import numpy as np

# Original array
arr = np.array([1.2, 2.5, 3.8])

print("Original dtype :", arr.dtype)

# Convert float array to integer array
int_arr = arr.astype(int)

print("Converted Array :", int_arr)
print("New dtype       :", int_arr.dtype)

### `astype()`

Converts an array to the specified data type.

**Syntax**

```python
arr.astype(dtype)
```

Example:

```python
arr.astype(int)
```

Converts all elements to integers.

> **Note:** When converting `float` to `int`, the decimal part is **truncated** (not rounded).

# 📘 Chapter 6 — Arithmetic Operations on Arrays

### Arithmetic Operations

NumPy supports **element-wise arithmetic operations**.

When an operator is applied to an array, the operation is performed on **each element** automatically.

In [6]:
import numpy as np

arr = np.array([10, 11, 234])

print(arr + 6)
print(arr * 3)
print(arr ** 2)

[ 16  17 240]
[ 30  33 702]
[  100   121 54756]


The operation is applied to every element of the array.

```python
arr + 6
```

Adds `6` to each element.

```python
arr * 3
```

Multiplies each element by `3`.

```python
arr ** 2
```

Squares each element.

### NOTES_

Supported arithmetic operators:

- `+` → Addition
- `-` → Subtraction
- `*` → Multiplication
- `/` → Division
- `**` → Power (Exponent)

# 📘 Chapter 7 — Aggregation Functions

### Aggregation Functions

Aggregation functions summarize the data in an array by returning a **single value**.

In [ ]:
import numpy as np

arr = np.array([10, 23, 20, 34, 30, 40])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

| Function | Purpose |
|----------|---------|
| `np.sum()` | Returns the sum of all elements |
| `np.mean()` | Returns the average |
| `np.min()` | Returns the smallest element |
| `np.max()` | Returns the largest element |
| `np.std()` | Returns the standard deviation |
| `np.var()` | Returns the variance |

# 📘 Chapter 8 — Indexing & Fancy Indexing

### Indexing

Indexing is used to access elements from a NumPy array.

NumPy follows **0-based indexing**, where the first element has index `0`.

Types covered:

- Basic Indexing
- Negative Indexing
- Fancy Indexing

In [ ]:
import numpy as np

arr = np.array([10, 20, 23, 450, 87, 90])

print(arr[0])    # First element
print(arr[2])    # Third element
print(arr[-1])   # Last element

### Basic Syntax

**1D Array**

```python
arr[index]
```

Examples:

```python
arr[0]     # First element
arr[2]     # Third element
arr[-1]    # Last element
```

Negative indexing starts from the end of the array.

### **BUT IN SLICING** - we selecet multiple element at a time and 
### **in INDEXING** - we select 1 item a time .

- indexing --> ` arr[index]`
---
- slicing -->  `arr[start : stop : step]`
* eg ->         `arr[start:end] --> start to end -1`
* eg ->         `negative step = -1`

### Fancy Indexing

Selects multiple elements using a list of indices.

**Syntax**

```python
arr[[index1, index2, index3]]
```

Example:

```python
arr[[0, 2, 4]]
```

Output:

```python
[10 30 50]
```

Unlike slicing, the indices **do not need to be consecutive**.

In [ ]:
## FANCY INDEXING
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(arr[[0, 2, 4]])

[10 30 50]


# 9. 📘 Boolean Masking / Filtering

# FILTERING / BOOLEAN MASKING

Boolean Masking is used to **filter data** using comparison operators.

Common operators:

- `>`
- `<`
- `>=`
- `<=`
- `==`
- `!=`

> **NOTE**
>
> - Returns only the elements that satisfy the given condition.
> - Much faster than using loops for filtering.
> - Commonly used in Data Analysis and Machine Learning.

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(arr[arr > 25])

[30 40 50 60 70 80 90]


### Syntax

```python
arr[condition]
```

Example:

```python
arr[arr > 25]
```

Returns all elements greater than `25`.

In [10]:
array = np.arange(11, 21)

print(array)

bool_index = array % 2 == 0

print(bool_index)

array2 = array[bool_index]

print(array2)

[11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


### Step 1

```python
array % 2 == 0
```

Checks every element.

Returns a Boolean array (`True` / `False`).

---

### Step 2

```python
array[bool_index]
```

Only the elements with `True` are selected.

Output:

```python
[12 14 16 18 20]
```

# 10 . 📘 Slicing

### SLICING

Slicing is used to access **multiple elements** (subset of data) from an array.

Syntax

```python
arr[start : stop : step]
```

### NOTE -->

- **start** → Starting index (Default = `0`)
- **stop** → Ending index (**excluded**)
- **step** → Skip elements (Default = `1`)
- Negative step (`-1`) is used to traverse in reverse direction.

Examples

```python
arr[1:6]      # index 1 to 5
arr[1:10:2]   # index 1,3,5,7,9
```

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,23])

print(arr[0:8:2])
print(arr[-4:-1])

print(arr[1:])      # Start only
print(arr[:4])      # Stop only
print(arr[::2])     # Step only

# Reverse the array
print(arr[::-1])

[1 3 5 7]
[10 11 12]
[ 2  3  4  5  6  7  8  9 10 11 12 23]
[1 2 3 4]
[ 1  3  5  7  9 11 23]
[23 12 11 10  9  8  7  6  5  4  3  2  1]


```python
arr[1:]
```

→ From index `1` to the end.

---

```python
arr[:4]
```

→ From beginning to index `3`.

---

```python
arr[::2]
```

→ Select every 2nd element.

---

```python
arr[::-1]
```

→ Reverse the entire array.
```

## 2D Slicing Syntax

```python
arr[row_slice, column_slice]
```

Examples

```python
arr[0:2,1:3]
```

→ Rows `0-1`, Columns `1-2`

---

```python
arr[3:,3:]
```

→ From 4th row & 4th column to the end.

---

```python
arr[:,2]
```

→ Select the **entire 3rd column**.
```

In [ ]:
import numpy as np

arr = np.arange(1,31).reshape(6,5)
print(arr)

# First 2 rows and columns 2 to 3
print(arr[0:2, 1:3])

# From 4th row to last and 4th column to last
print(arr[3:, 3:])

# Entire 3rd column
print(arr[:, 2])

# 11. COPYING ARRAYS (Assignment, View & Deep Copy)

## NOTE -->

When we create another array from an existing array, there are **3 ways**:

1. **Assignment (`=`)** → Same memory (Reference)
2. **Slicing (`arr[:]`)** → View (Shallow Copy)
3. **`copy()`** → Deep Copy (New Memory)

---

In [13]:
## Example 1 --> Assignment (`=`)
import numpy as np

arr = np.arange(1, 21)

b = arr      # Assignment

b[0] = 9999

print("Original Array :", arr)
print("Assigned Array :", b)

Original Array : [9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20]
Assigned Array : [9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20]


In [ ]:
b = arr.copy()   # Deep copy (independent)
c = arr.view()   # Shallow copy (linked)

### Explanation -->

* `b = arr` does **not** create a new array.
* Both variables point to the **same memory**.
* Any change in `b` also changes `arr`.

In [ ]:
## Example 2 --> Slicing (View / Shallow Copy)

arr = np.arange(1, 21)

slice_arr = arr[:5]

slice_arr[0] = 100  # it also effect original array

print("Original Array :", arr)
print("Slice Array    :", slice_arr)
print("Original Array :", arr)

Original Array : [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
Slice Array    : [100   2   3   4   5]
Original Array : [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


### Explanation -->

* Slicing creates a **View (Shallow Copy)**.
* A view shares the same memory as the original array.
* Changing the slice also changes the original array.


In [50]:
# Example 3 Deep Copy --> (copy()) 
arr = np.arange(1, 21)

b = arr.copy()

b[0] = 9999

print("Original Array :", arr)
print("Copied Array   :", b)

Original Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Copied Array   : [9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20]




### Explanation -->

* `copy()` creates a completely new array.
* Original and copied arrays have different memory locations.
* Changing one array does **not** affect the other.
---


## NOTE -->

| Method             | Memory      | Original Array Changes? |
| ------------------ | ----------- | ----------------------- |
| `b = arr`          | Same        | ✅ Yes                   |
| `arr[:]` / Slicing | Same (View) | ✅ Yes                   |
| `arr.copy()`       | New         | ❌ No                    |
---

# 12. MATRIX OPERATIONS



## NOTE -->

NumPy provides built-in operations for matrices.

In this topic:

* Matrix Multiplication
* Transpose

---

## 1. Matrix Multiplication

### Syntax -->

```python
A @ B

# OR

np.dot(A, B)


In [16]:

### Example -->
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

print(np.dot(A, B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Explanation -->

* `@` is the matrix multiplication operator.
* `np.dot()` also performs matrix multiplication for 2D arrays.
* Both give the same result.

### 2. Transpose

### Syntax -->

```python
A.T
```


In [17]:

### Example -->
print(A.T)

[[1 3]
 [2 4]]


### Explanation -->

* `.T` returns the transpose of a matrix.
* Rows become columns and columns become rows.
* `.T` is an **attribute**, so it does **not** use `()`.


# 📘 13. Reshaping



## NOTE -->

- Reshaping means changing the shape (dimensions) of an array **without changing the data**.
- Total number of elements must remain the same.
- `reshape()` returns a **view** whenever possible (does not copy the data).
- New shape is given as `(rows, columns)`.

Example:

```
6 elements

(2 × 3) ✅
(3 × 2) ✅
(1 × 6) ✅
(6 × 1) ✅
(4 × 2) ❌
```

- **Reshaping is technique to change the shape or dimension of an any array without modifying the data**  
- eg --> 
`suppose we gonna conert 1D ARRAY into -> 2D ARRAY and vice versa, But we don't want to modify the data .`

- #--> `reshaping means changing the dimension of the dataset of withthout  modifly original data`.
- #--> `if there is 4 element in data after reshaping the data also 4 elements in data.`
- #--> `it return the view  of dataset.` 
### --> **it does not copy the data  --> it returns a view**

- **NOTE** --> `we only reshape only when dimension is match. `

- SYNTAX--> 
- #--> **`reshape(rows, column) `** specify new shape

- #--> **`arr.reshape(row,column)`**

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])  # here dimension is match => 3+3 = 6 element
# if we pick (5,7,9),etc element and reshape into (2,3) then it show ❌ ERROr

reshaped_arr = arr.reshape(2,3)   # 2 row , 3 column
print(reshaped_arr)

## Explanation -->

### `reshape()`

**Syntax**

```python
arr.reshape(rows, columns)
```

Example

```python
arr.reshape(2, 3)
```

Returns a new shape:

```
[[1 2 3]
 [4 5 6]]
```

### NOTE -->

- Original data does not change.
- Number of elements must remain the same.
- Usually returns a **view** (shares memory with the original array).

## Cheat Sheet Update -->

| Method | Purpose |
|--------|---------|
| `reshape()` | Change the shape of an array |

### Remember -->

```
rows × columns = Total Elements
```

# 14. Flattening Array



## NOTE -->

Last topic we learned how to convert a **1D array → Multi-dimensional array** using `reshape()`.

Now we learn how to convert a **Multi-dimensional array → 1D array**.

There are two methods:

1. `ravel()`
   - Returns a **View** of the original array.
   - Changes may affect the original array.

2. `flatten()`
   - Returns a **Copy** of the original array.
   - Changes do **not** affect the original array.

In [19]:
import numpy as np

arr_2d = np.array([
    [1, 3, 4, 2],
    [5, 6, 7, 8]
])

print(arr_2d.ravel())

print(arr_2d.flatten())

[1 3 4 2 5 6 7 8]
[1 3 4 2 5 6 7 8]


In [51]:
a = np.array([[1,2],[3,4]])

b = a.ravel()

b[0] = 100

print(a)
print(b)


# Now a also changes because b is a view.

[[100   2]
 [  3   4]]
[100   2   3   4]


## Explanation -->

### `ravel()`

**Syntax**

```python
arr.ravel()
```

- Converts a multi-dimensional array into a **1D array**.
- Returns a **View** whenever possible.
- Original array **may be affected** if the returned array is modified.

---

### `flatten()`

**Syntax**

```python
arr.flatten()
```

- Converts a multi-dimensional array into a **1D array**.
- Always returns a **Copy**.
- Original array is **not affected**.

## Cheat Sheet Update -->

| Method | Returns | Original Array |
|---------|----------|----------------|
| `ravel()` | View | May change |
| `flatten()` | Copy | Not affected |

# 📘15. Modification - Inserting



## NOTE -->

In real-world datasets, data keeps changing.

Sometimes we need to:

- Add new values
- Remove values
- Merge datasets
- Split datasets

Unlike Python Lists, **NumPy Arrays have a fixed size**.

So, operations like insert or delete create a **new array** instead of modifying the original array.

In [21]:
import numpy as np

# 1D Array
arr = np.array([10, 20, 30, 40, 50, 60])

new_arr = np.insert(arr, 2, 100)

print("New Array :", new_arr)
print("Old Array :", arr)

New Array : [ 10  20 100  30  40  50  60]
Old Array : [10 20 30 40 50 60]


## Explanation -->

### `np.insert()`

**Syntax**

```python
np.insert(array, index, value, axis=None)
```

### NOTE -->

- Returns a **new array**.
- Original array is **not changed**.
- If `axis` is not given (`None`), the array is flattened first.

In [22]:
# 2D Array

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Insert a row
new_row = np.insert(arr_2d, 1, [5, 6, 7], axis=0)

print(new_row)

# Insert a column
new_col = np.insert(arr_2d, 3, [99, 99], axis=1)

print(new_col)

[[1 2 3]
 [5 6 7]
 [4 5 6]]
[[ 1  2  3 99]
 [ 4  5  6 99]]


## NOTE -->

### `axis = 0`

Insert **row(s)**.

---

### `axis = 1`

Insert **column(s)**.

In [23]:
# axis = None

new = np.insert(arr_2d, 3, [99, 99], axis=None)

print(new)

[ 1  2  3 99 99  4  5  6]


## NOTE -->

When `axis=None`:

- NumPy first converts the array into a **1D array**.
- Then it inserts the value at the given index.

Example:

```python
np.insert(arr_2d, 3, [99, 99], axis=None)
```

Output

```python
[ 1  2  3 99 99  4  5  6]
```

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.insert()` | Insert value(s) into an array |

### Axis -->

| Axis | Meaning |
|------|---------|
| `axis=0` | Insert row(s) |
| `axis=1` | Insert column(s) |
| `axis=None` | Flatten array first, then insert |

## Remember -->

axis = 0 → Row

axis = 1 → Column

## Remember -->

NumPy Array = Fixed Size

Insert/Delete
        ↓
Creates a New Array

# 📘16 Append



## NOTE -->

`append()` is used to add value(s) at the **end** of an array.

- Adds element(s) at the last.
- Returns a **new array**.
- Original array remains unchanged.

**Syntax**

```python
np.append(array, values, axis=None)
```

In [24]:
import numpy as np

arr = np.array([10, 30, 40, 50])

new_arr = np.append(arr, [20, 60, 99])

print("New Array :", new_arr)
print("Old Array :", arr)

New Array : [10 30 40 50 20 60 99]
Old Array : [10 30 40 50]


## Explanation -->

### `np.append()`

- Adds value(s) at the **end** of an array.
- Returns a **new array**.
- Original array is **not changed**.

Output

```python
[10 30 40 50 20 60 99]
```

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.append()` | Add value(s) at the end of an array |

### Remember -->

- `insert()` → Add at a specific index.
- `append()` → Add at the end.

*  Instead of repeating the syntax in both Insert and Append, we can make the notebook flow naturally:

- Insert → "Add at any position."
- Append → "Add at the last position."

Then later, in the Final Cheat Sheet, we'll compare them together:

| Function      | Position     |
| ------------- | ------------ |
| `np.insert()` | Any index    |
| `np.append()` | End of array |


# 17. # Concatenate



## NOTE -->

`concatenate()` is used to join **two or more arrays** into a single array.

**Syntax**

```python
np.concatenate((array1, array2), axis=0)
```

### Axis -->

- `axis = 0` → Join along **rows** (default)
- `axis = 1` → Join along **columns** (Only for 2D or higher arrays)

In [25]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.concatenate((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


## Explanation -->

### `np.concatenate()`

Joins two or more arrays into a single array.

Output

```python
[1 2 3 4 5 6]
```

> **NOTE**
>
> For **1D arrays**, `axis=0` (or default) is used.

In [52]:
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([4, 5])

# This will give an error
# np.concatenate((arr1, arr2), axis=1)

## NOTE -->

Why Error?

- `arr1` and `arr2` are **1D arrays**.
- `axis=1` means join along **columns**.
- But a 1D array has no columns.

So `axis=1` is **not valid** for 1D arrays.

In [27]:
# Convert 1D arrays into 2D

arr1 = np.array([1, 2]).reshape(2, 1)
arr2 = np.array([4, 5]).reshape(2, 1)

new_arr = np.concatenate((arr1, arr2), axis=1)

print(new_arr)

[[1 4]
 [2 5]]


## Explanation -->

After `reshape(2,1)`

Shape of both arrays becomes:

```python
(2,1)
```

Now `axis=1` joins the arrays **column-wise**.

Output

```python
[[1 4]
 [2 5]]
```

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.concatenate()` | Join two or more arrays |

### Remember -->

- `axis=0` → Join rows
- `axis=1` → Join columns
- `axis=1` works only for **2D or higher** arrays.

# 18. # Delete



## NOTE -->

`delete()` is used to remove element(s) from an array.

- Returns a **new array**.
- Original array remains unchanged.

**Syntax**

```python
np.delete(array, index, axis=None)
```

### Axis -->

- `axis=None` → Delete element(s) from a flattened (1D) array.
- `axis=0` → Delete row(s).
- `axis=1` → Delete column(s).

In [28]:
import numpy as np

# 1D Array
arr = np.array([1, 34, 232, 56, 32, 78, 96])

new_arr = np.delete(arr, 2)

print("New Array :", new_arr)
print("Old Array :", arr)

New Array : [ 1 34 56 32 78 96]
Old Array : [  1  34 232  56  32  78  96]


## Explanation -->

### `np.delete()`

Deletes element(s) from an array.

```python
np.delete(arr, 2)
```

Deletes the element at **index 2**.

> **NOTE**
>
> Original array is **not changed**.

In [29]:
# 2D Array

arr2d = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 7]
])

# Delete 1st row
print(np.delete(arr2d, 0, axis=0))

# Delete 2nd row
print(np.delete(arr2d, 1, axis=0))

[[4 5 6 7]]
[[1 2 3 0]]


## NOTE -->

### `axis = 0`

Deletes **row(s)**.

Index is based on the row number.

```
Row 0
Row 1
Row 2
...
```

In [30]:
# Delete columns

print(np.delete(arr2d, 0, axis=1))
print(np.delete(arr2d, 1, axis=1))
print(np.delete(arr2d, 2, axis=1))
print(np.delete(arr2d, 3, axis=1))

[[2 3 0]
 [5 6 7]]
[[1 3 0]
 [4 6 7]]
[[1 2 0]
 [4 5 7]]
[[1 2 3]
 [4 5 6]]


## NOTE -->

### `axis = 1`

Deletes **column(s)**.

Index is based on the column number.

```
Column 0
Column 1
Column 2
Column 3
...
```

In [31]:
# Original array remains unchanged

print(arr2d)

[[1 2 3 0]
 [4 5 6 7]]


## Remember -->

Think like an Excel sheet.

```
      Column
       0 1 2 3
     ┌─────────┐
Row0 │ 1 2 3 0 │
Row1 │ 4 5 6 7 │
     └─────────┘
```

- `axis=0` → Select **rows**
- `axis=1` → Select **columns**

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.delete()` | Delete element(s), row(s), or column(s) |

### Remember -->

- `axis=None` → Flatten first, then delete.
- `axis=0` → Delete row(s).
- `axis=1` → Delete column(s).

# 📘19 Stacking


## NOTE -->

Stacking means combining **two or more arrays** into a single array.

Types of stacking:

1. `vstack()` → Stack row-wise (Vertical)
2. `hstack()` → Stack column-wise (Horizontal)
3. `column_stack()` → Stack 1D arrays as columns

In [32]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 7])

print(np.vstack((arr1, arr2)))

[[1 2 3]
 [5 6 7]]


## Explanation -->

### `np.vstack()`

Stacks arrays **row-wise**.

Output

```python
[[1 2 3]
 [5 6 7]]
```

In [33]:
print(np.hstack((arr1, arr2)))

[1 2 3 5 6 7]


## Explanation -->

### `np.hstack()`

Stacks arrays **column-wise**.

For **1D arrays**, it joins them into a single array.

Output

```python
[1 2 3 5 6 7]
```

In [34]:
print(np.column_stack((arr1, arr2)))

[[1 5]
 [2 6]
 [3 7]]


## Explanation -->

### `np.column_stack()`

Stacks 1D arrays as **columns**.

Output

```python
[[1 5]
 [2 6]
 [3 7]]
```

vstack()

[1 2 3]
[5 6 7]

      ↓

[[1 2 3]
 [5 6 7]]

---

hstack()

[1 2 3]

[5 6 7]

      ↓

[1 2 3 5 6 7]

---


column_stack()

[1 2 3]
[5 6 7]

      ↓

[[1 5]
 [2 6]
 [3 7]]

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.vstack()` | Stack arrays row-wise |
| `np.hstack()` | Stack arrays horizontally |
| `np.column_stack()` | Stack 1D arrays as columns |

### Remember -->

- `vstack()` → Vertical
- `hstack()` → Horizontal
- `column_stack()` → Columns

# 📘 20.Splitting

## NOTE -->

Splitting means dividing an array into **multiple sub-arrays**.

Functions:

1. `np.split()` → Split into equal parts.
2. `np.hsplit()` → Split column-wise.
3. `np.vsplit()` → Split row-wise.

In [35]:
import numpy as np

arr = np.array([1,2,3,3,5,6,7,8,90,12,3,4,54,65])

print(np.split(arr, 2))


[array([1, 2, 3, 3, 5, 6, 7]), array([ 8, 90, 12,  3,  4, 54, 65])]


## Explanation -->

### `np.split()`

**Syntax**

```python
np.split(array, sections)
```

### NOTE -->

- Splits the array into **equal parts**.
- Number of elements must be divisible by the number of sections.

Example

```
14 elements

Split into 2 ✅
Split into 7 ✅
Split into 3 ❌
```

In [36]:
print(np.hsplit(arr, 2))

[array([1, 2, 3, 3, 5, 6, 7]), array([ 8, 90, 12,  3,  4, 54, 65])]


## Explanation -->

### `np.hsplit()`

Splits an array **column-wise**.

For a **1D array**, it behaves like `np.split()`.

In [37]:
# 1D array

# print(np.vsplit(arr, 2))

# ValueError:
# vsplit only works on arrays of 2 or more dimensions

## NOTE -->

`np.vsplit()` works only with **2D or higher-dimensional arrays**.

In [38]:
arr2d = np.arange(1,17).reshape(4,4)

print(arr2d)

print(np.hsplit(arr2d, 2))

print(np.vsplit(arr2d, 2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


## Explanation -->

### `np.hsplit()`

Splits the array **column-wise**.

```
4 × 4

↓

4 × 2   +   4 × 2
```

---

### `np.vsplit()`

Splits the array **row-wise**.

```
4 × 4

↓

2 × 4   +   2 × 4
```

## Cheat Sheet Update -->

| Function | Purpose |
|----------|---------|
| `np.split()` | Split array into equal parts |
| `np.hsplit()` | Split column-wise |
| `np.vsplit()` | Split row-wise |

### Remember -->

- `split()` → Equal parts
- `hsplit()` → Horizontal split (columns)
- `vsplit()` → Vertical split (rows)

# 📘 21 . Broadcasting 

## NOTE -->

Broadcasting is a NumPy feature that allows -  arrays of **different different but compatible shapes** to perform operations **without using loops**.

Advantages:

- No loops required.
- Less code.
- Faster execution.
- Automatic element-wise operations whenever possible.

- > Braodcasting is a features of  Numpy  where we perform differrent operation on different different shapes of an arrray witout using loops
- altough size of array is small or big Numpy do it quickly and easily.
- **here we don't write more line of code**

- `QUESTION` HOW NUMPY HANDLE DIFFERENT SHAPES OF ARRAY ?

- > Basically there are 3 rule for broadcasting 

1. Matching dimension == means if both array is same shape then we apply element wise operartion normally.
eg-->> [1,2,3] + [4,5,6] == [5,7,9]


2. Expanding single element --> if one array  has in one dimension then numpy expand it so it  match from another array.
eg-- a = [1,2,3]
.    b = [10 ]
so here numpy can add (2nd array single elemnet) 10 on every element of 1st array.  
then -->> output is , c= [11,12,13] 



3. Incompatitable shape   -->> if shape of two array doesnot match then it show error.
eg -- a= [1,2,3]
.     b = [4,5]  numpy cant perfomr any operatiion because it shape does not match.
  '''


In [ ]:
# Using Python Loop

prices = [100, 200, 300]

discount = 10

final_prices = []

for price in prices:
    final_p = price - (price * discount / 100)
    final_prices.append(final_p)

print(final_prices)

[90.0, 180.0, 270.0]


## NOTE -->

Using loops works correctly, but it becomes slow for large datasets.

In [40]:
# Using NumPy Broadcasting

import numpy as np

prices = np.array([100, 200, 300])

discount = 10

final_prices = prices - (prices * discount / 100)

print(final_prices)

[ 90. 180. 270.]


## Explanation -->

Here `discount` is a **scalar value**.

NumPy automatically applies the operation to every element of the array.

No loop is required.

# Broadcasting Rules

## Rule 1 --> Matching Shapes

If both arrays have the same shape, NumPy performs **normal element-wise operations**.

Example

```python
[1,2,3] + [4,5,6]

↓

[5,7,9]
```

---

## Rule 2 --> Expanding Single Element

If one value (or dimension) is `1`, NumPy automatically expands it.

Example

```python
[1,2,3] + [10]

↓

[11,12,13]
```

---

## Rule 3 --> Incompatible Shapes

If shapes are not compatible, NumPy raises an error.

Example

```python
(2,3)

+

(2,)
```

❌ ValueError

In [41]:
# Rule 1

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

vector = np.array([10,20,30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


## Explanation -->

Shape of matrix

```
(2,3)
```

Shape of vector

```
(3,)
```

NumPy automatically broadcasts the vector to each row.

Output

```python
[[11 22 33]
 [14 25 36]]
```

In [42]:
# Rule 2

a = np.array([1,2,3])

b = np.array([10])

print(a + b)

[11 12 13]


## NOTE -->

`10` is automatically used for every element.

Output

```python
[11 12 13]
```

In [ ]:
# Rule 3

arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

arr2 = np.array([1,2])

# print(arr1 + arr2)
# ERROR

## NOTE -->

Shape of `arr1`

```
(2,3)
```

Shape of `arr2`

```
(2,)
```

These shapes are **not compatible**.

Output

```python
ValueError:
operands could not be broadcast together
```

> **NOTE**
>
> `reshape()` may solve the problem **only if the new shape is compatible**. It is **not** a universal solution.

# 📘22.Vectorization



## NOTE -->

Vectorization means performing an operation on the **entire array at once** without using loops.

Advantages:

- No loops required.
- Less code.
- Faster execution than traditional loops.
- Used for mathematical and matrix operations.

In [44]:
# Traditional Way (Using Loop)

list1 = [1, 2, 3]
list2 = [4, 5, 6]

result = [x + y for x, y in zip(list1, list2)]

print(result)

[5, 7, 9]


## NOTE -->

This is the traditional Python way.

It works well for small data but becomes slower for large datasets.

In [45]:
# Vectorization

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([11, 23, 45])

result = arr1 + arr2

print(result)

[12 25 48]


## Explanation -->

The operation is applied to the **entire array at once**.

No loop is required.

In [46]:
# Another Example

arr = np.array([10, 23, 45])

print(arr * 3)

[ 30  69 135]


## NOTE -->

Every element is multiplied by `3` automatically.

No loop is required.

# Broadcasting vs Vectorization

| Broadcasting | Vectorization |
|--------------|---------------|
| Handles arrays of compatible shapes | Performs operation on the entire array |
| Automatically expands compatible dimensions | Applies one operation to all elements |
| Used when array shapes are different but compatible | Used for fast array computations |
| No loops | No loops |

## Remember -->


Traditional Way

Loop
   ↓
One element at a time
   ↓
Slower

----------------------------

Vectorization

Whole Array
     ↓
One Operation
     ↓
Faster

## Remember -->

` and for Broadcasting --> `

Broadcasting

Different Shapes
        ↓
Compatible?
   ↓          ↓
 Yes         No
 ↓            ↓
Operation    Error

# `Handling Missing & Infinite Values` #

###  SOME FUNCTION FOR DATA HANDELING --->
- detect missing vlue. --> np.isnan(arr) 
- change detected missing  value with another values--> np.nan_to_num(array, nan = value) | default = 0
- detect infinite value --> np.isinf(arr)
- change infine into finite value ---> np.nan_to_num(arr2, posinf =100, neginf = 200)

In [ ]:
np.isnan(arr)                            # Detect NaN
np.nan_to_num(arr, nan=0)                # Replace NaN
np.isinf(arr)                            # Detect infinite
np.nan_to_num(arr, posinf=100, neginf=-100)  # Replace infinities
np.nanmean(arr)                          # Mean ignoring NaN


NOW
----------


# we have some more function of NumPy are-->

## 23. Random Module ⭐

In [ ]:
np.random.rand()
np.random.randn()
np.random.randint()
np.random.choice()
np.random.seed()
np.random.shuffle()
np.random.permutation()

## 24. Searching Functions ⭐

In [ ]:
np.where()

np.argmax()

np.argmin()

np.nonzero()

np.searchsorted()

## 25. Sorting ⭐

In [ ]:
np.sort()

np.argsort()

## 26. Unique Values ⭐

In [ ]:
np.unique()

np.count_nonzero()

## 27. Mathematical Functions ⭐ 

In [ ]:
np.sqrt()

np.power()

np.abs()

np.exp()

np.log()

np.sin()

np.cos()

np.round()

np.floor()

np.ceil()

## 29. Logical Functions ⭐

In [ ]:
np.any()

np.all()

np.logical_and()

np.logical_or()

np.logical_not()

## 30. Iterating Arrays ⭐

In [ ]:
np.nditer()

np.ndenumerate()

## 31. Saving & Loading Arrays ⭐-->

1. np.save() --> # Save in .npy format

2. np.load()  --> # Load .npy file

3. np.savetxt()  --> # Save CSV

4. np.loadtxt() --> # Load CSV

In [ ]:
np.save('file.npy', arr)                 # Save in .npy format
np.load('file.npy')                      # Load .npy file

np.savetxt('file.csv', arr, delimiter=',')  # Save CSV
np.loadtxt('file.csv', delimiter=',')       # Load CSV


## 32. Array Creation ⭐ (which i had left.)


In [ ]:
np.empty()

np.identity()

np.diag()

## 33. Conditional Functions ⭐

In [ ]:
np.where()

np.clip()

np.select()

## 34.  And some more `Advanced` (Optional) ⭐

1. Linear Algebra (np.linalg)

2. inverse()

3. determinant()

4. eigenvalues()

5. solve()

6. norm()

7. matrix_rank()

# SHORT CHEATSHEET --->  

# Short cheatsheet by me i know its not complete but -- jitna mujhe yyad aay or samjh aya maine likhe diya 

##### import numpy as np   > (first we have to import numpy like that)

1. **Array Creation**
- `variable = np.array([data])`

---
2. **operation**
- creating identity matrix -->          np.eye(no.)
-  making 2 *2 matrix with value 1 -->       np.one(2,2)
-  making 2 *3  matrix with value 0 -->      np.zeros(2,3)
-  making 3 *4  matrix with value 7 -->        np.full(3,4)(7)
---
3. **Array Attributes**
- `REMEMBER` --> `shape` `size` `ndim` `dtype` -> ke sath `parenthesis ()` **NHI** ❌ aata hai..
---
4. **Change dtype**  -->  `arr.astype(int,float,etc)`
---
5. **Reshaping** 
- reshaping/change dimension of dataset without changng original datset --> arr.reshape(row,column)
---
6. **Mathematical Operation** -
# Mathematical Operations

1. `np.sum(arr)`                    >        **# Sum**
2. `np.mean(arr)`                   >        **# Mean**
3. `np.std(arr)`                    >        **# Standard deviation**
4. `np.max(arr)`                    >        **# Max value**
5. `np.min(arr)`                    >        **# Min value**
6. `np.argmax(arr)`                 >        **# Index of max**
7. `np.argmin(arr)`                 >        **# Index of min**
8. `arr + 5`                        >        **# Add scalar**
9. `arr1 + arr2`                    >        **# Element-wise addition**
10. `arr1 @ arr2`                   >        **# Matrix multiplication**
11. `np.dot(arr1, arr2)`            >        **# Matrix multiplication**
12. `arr.T`                         >        **# transpose of matrix**
13. `arr1 + arr2`                   >        **# add two whole array** 


---
7.  **Modify Arrays** 
- np.insert(arr, 2, 100)                   # Insert 100 at index  2 in arr
- np.append(arr, [20, 60])                 # Append values at last
- np.delete(arr, 2)                        # Delete element
---
8. **Broadcasting**
- here `we add two array` , `match dimension between arrays`, `expand single element` ,etc 

---
9. **copy vs view**
- b = arr.copy()   # Deep copy (independent)
- c = arr.view()   # Shallow copy (linked)

---

10.  **Save and loading FIle**
- np.save('file.npy', arr)                 # Save in .npy format
- np.load('file.npy')                      # Load .npy file

- np.savetxt('file.csv', arr, delimiter=',')  # Save CSV
- np.loadtxt('file.csv', delimiter=',')       # Load CSV
---

11. **Handeling** >  `missing value` and `Infinite value`  
- detect missing vlue. --> np.isnan(arr) 
- change detected missing  value with another values--> np.nan_to_num(array, nan = value) | default = 0
- detect infinite value --> np.isinf(arr)
- change infine into finite value ---> np.nan_to_num(arr2, posinf =100, neginf = 200)







In [ ]:
np.array([1, 2, 3])                       # 1D array
np.array([[1, 2], [3, 4]])                 # 2D array
np.zeros((2, 3))                           # 2x3 matrix of 0s
np.ones((2, 2))                            # 2x2 matrix of 1s
np.full((3, 4), 7)                         # 3x4 matrix filled with 7
np.eye(3)                                  # Identity matrix (3x3)
np.arange(1, 10, 2)                        # [1, 3, 5, 7, 9]  # arrange element 1 to 10 step =2:
np.linspace(0, 1, 5)                       # 5 evenly spaced numbers from 0 to 1
arr = np.arange(1,17)
arr.shape       # (rows, cols)
arr.size        # total elements
arr.ndim        # dimensions
arr.dtype       # data type

#Change Data Type

arr.astype(float)
import numpy as np
arr = np.array([1.2, 2.5, 3.8])

print("Original dtype :", arr.dtype)
int_arr = arr.astype(int)

print("Converted Array :", int_arr)
print("New dtype       :", int_arr.dtyp)


arr.reshape(3, 4)                       # Change shape (returns new array)
arr.T                                   # Transpose
arr.flatten()                           # 1D copy
arr.ravel()                             # 1D view (linked to original)
arr[:, np.newaxis]                      # Add new dimension


# Mathematical operation -
np.sum(arr)                             # Sum
np.mean(arr)                            # Mean
np.std(arr)                             # Standard deviation
np.max(arr)                             # Max value
np.min(arr)                             # Min value
np.argmax(arr)                          # Index of max
np.argmin(arr)                          # Index of min
arr + 5                                 # Add scalar
arr1 + arr2                             # Element-wise addition
arr1 @ arr2                             # Matrix multiplication
np.dot(arr1, arr2)                      # Matrix multiplication
arr.T                                    # transpose of matrix
arr1 + arr2                              # add two whole array 

# modify  arrays
np.insert(arr, 2, 100)                   # Insert 100 at index  2 in arr
np.append(arr, [20, 60])                 # Append values at last
np.delete(arr, 2)                        # Delete element

## Broadcasting--
arr + 5                                  # Add scalar to all elements
arr + np.array([1, 2, 3])                # Add per column/row

## Copy vs view 
b = arr.copy()   # Deep copy (independent)
c = arr.view()   # Shallow copy (linked)

## Save and load FIle -->
np.save('file.npy', arr)                 # Save in .npy format
np.load('file.npy')                      # Load .npy file

np.savetxt('file.csv', arr, delimiter=',')  # Save CSV
np.loadtxt('file.csv', delimiter=',')       # Load CSV

## Handeling -- Missing  and infinite value -->
np.isnan(arr)                            # Detect NaN
np.nan_to_num(arr, nan=0)                # Replace NaN
np.isinf(arr)                            # Detect infinite
np.nan_to_num(arr, posinf=100, neginf=-100)  # Replace infinities
np.nanmean(arr)                          # Mean ignoring NaN


